name: Dockerize FreeFileSync

on:
  push:

jobs:
  build-container:
    name: Docker Image build and publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: sirflip/freefilesync
        tags: latest
